apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-ingress
  annotations:
    alb.ingress.kubernetes.io/group.name: helloworld
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - host: hello.smallsmallbird.xyz
    http:
      paths:
      - path: /
        backend:
            serviceName: helloworld-service
            servicePort: 32123
